### ISSUE TITLE
Protect sensitive credentials and keys using Windows crypto API

### ISSUE THREAD

**Issue by Rondom** [viciousviper/DokanCloudFS#17]
For additional security the keys and the login-tokens could be stored encrypted.

https://en.wikipedia.org/wiki/Data_Protection_API
https://msdn.microsoft.com/en-us/library/system.security.cryptography.protecteddata(v=vs.110).aspx

**Comment by viciousviper** [comment]
Thanks for bringing up this issue and suggesting a potential approach to its solution.
Instead of entirely obfuscating all of the application settings by encrypting the settings files I am working on a solution to specifically encrypt account credentials and access tokens through AES.
The scheme has been put in place in the CloudFS project, and I'll connect it to DokanCloudFS next.

**Comment by viciousviper** [comment]
Fixed with [v1.0.8-alpha](https://github.com/viciousviper/DokanCloudFS/releases/tag/v1.0.8-alpha).
Please check if this works for you.
