### ISSUE TITLE
Paste or drop file action [question]

### ISSUE THREAD

**Issue by drunkenbeaver** [viciousviper/DokanCloudFS#23]
I mounted Box gateway and I can perform multiple operations like Creating directories, renaming them,.. but can't manage to simply paste some file that already doesn't exist in my Box cloud.

Is this part of Dokan and somehow doesn't work for my account, or for that purposes I need to use different approach (e.g. shell extensions?)?

No WriteFile event is happening, and "There is not enough space on box,..." message is popping.

Thanks

**Comment by viciousviper** [comment]
Hi @drunkenbeaver,

you are most likely falling victim to a curious bug/wierd behaviour in *Windows Explorer* which I haven't quite been able to nail down so far.
As it turns out, you can drag'n drop to your heart's delight **as long as the previously used space on the target drive you are pasting to is greater than or equal to the size of the file you are pasting**. At least this is what I've witnessed so far.
Could you do me a favor and try to verify this condition on your environment? The size constraint really only affects *Windows Exporer* - you should be able to *xcopy* files to the cloud drive with no problem at all.

Cheers
vv

**Comment by drunkenbeaver** [comment]
At first I haven't entirely understood the part in bold,.. But now I got it. I played with 10 - 50 KB files and it works exactly as you are saying. Indeed **xcopy** works fine - regardless the previously used space on the target drive (summing up just sizes of files - excluding directories), but unfortunately that's not what users are 'typically' doing (including myself),... :)

Of course, very nice discovery!

So, you're pretty sure it's up to the Windows Explorer behavior, and not the Dokan's fault?

Thanks for such a quick reply and information you shared!
- Thumbs up for the whole project, really nice work!.

Best regards

**Comment by viciousviper** [comment]
Thanks for confirming my suspicion wrt. Windows Explorer's strange copying behavior.

I totally believe that this is not a problem for the Dokan 'Mirror' sample - because it does exactly what it is named after and just forwards FS API calls to another physical drive where conditions are just like what Windows Explorer expects.
However, DokanCloudFS is required to interpret FS API calls and associate them with cloud gateway responses - and apparently will get it wrong under the conditions cited above.

I have seen traces of the problem before with log level 'Info' activated. What happens is basically that 
- at a certain point in time - and this is before actually writing to the new file - WinExplorer asks the driver for the current value of 'used space' on the target drive
- now DokanCloudFS, lacking any psychic reading capacity, will faithfully report the currently used space - which will typically be zero for empty drives
- WinExplorer, unable to cope with the naked truth, will then proceed to raise the error you saw and claim insufficient free space.

I'll look into the problem for the next release of DokanCloudFS.

**Comment by viciousviper** [comment]
Hi @drunkenbeaver,

might I ask a favour of you - could you please re-verify the error using Dokany 1.0.1?
I just tried to get to the root of the matter using the Box and various other cloud storage gateways, but I suddenly couldn't reproduce the problem.

TIA, vv

**Comment by viciousviper** [comment]
Closed due to prolonged inactivity.
