### ISSUE TITLE
Local Files Option

### ISSUE THREAD

**Issue by shlatchz** [viciousviper/DokanCloudFS#7]
How do I enable the local files option (and not one of the cloud storage providers...)? Can it be used?

**Comment by viciousviper** [comment]
Should be entirely usable by including the following line in `App.config`:
```xml      
<drive schema="file" root="T:" encryptionKey="MyFileSecret&amp;I" />
```
inside the `<drives>` tag.

I haven't actually checked the file plugin in `DokanCloudFS` yet, but since it is regularly tested as part of the `CloudFS` suite I would definitely expect it to work.

Functionality will be comparable to the *Mirror* project in *Dokan.Net* except the File plugin offers additional AES encryption.

**Comment by viciousviper** [comment]
On second thought there is probably a missing location parameter in the App.config schema. Cloud storage volums won't need it because their location is determined by the account, whereas the File plugin needs a source path.
I'll add this in the next couple of days after I get the unit test suite for CloudOperations straightened out.

**Comment by viciousviper** [comment]
Hi @shlatchz,
the local files option you requested is now operational.
Please update both CloudFS and DokanCloudFS to version 1.0.2-alpha and edit the configuration for the *file* gateway in DokanCloudFS.Mounter's `App.config` as required. A brief documentation of the new *parameters* config attribute has been added to Readme.md.
Feel free to ask if there is anything else not working as it should.

**Comment by viciousviper** [comment]
Hello @shlatchz,

after some time spent fixing other parts in the code I just finished updating the local *FILE* gateway in *CloudFS*/*DokanCloudFS* to a tentative fully operational state.
At this time it is available for local compilation and will be part of the upcoming version 1.0.5-alpha.
I'll keep this issue open for a short while longer, so maybe you'd be willing to give the *FILE* gateway a spin and report your findings here.

TIA vv

**Comment by viciousviper** [comment]
Closed as obsolete
